/* ============================================================
   Uzcarsale — данные (агент data)
   Модельный ряд Chevrolet (UzAuto Motors + импорт) и объявления.
   Vanilla JS, подключается через <script src="js/data.js">.
   Курс для пересчёта: ~12 600 сум / $.
   ============================================================ */

window.UZ_MODELS = [
  {
    id: "cobalt",
    name: "Chevrolet Cobalt",
    tagline: "Народный седан Узбекистана",
    body: "Седан",
    priceFromUZS: 163800000,
    priceFromUSD: 13000,
    engine: "1.5 л, 106 л.с.",
    transmission: "6АТ / 5МТ",
    fuel: "Бензин/газ",
    description: "Самый продаваемый автомобиль страны: неприхотливый, ремонтопригодный и всегда ликвидный на вторичном рынке."
  },
  {
    id: "onix",
    name: "Chevrolet Onix",
    tagline: "Городской седан нового поколения",
    body: "Седан",
    priceFromUZS: 191500000,
    priceFromUSD: 15200,
    engine: "1.0 л турбо, 116 л.с.",
    transmission: "6АТ",
    fuel: "Бензин",
    description: "Современный турбомотор, мультимедиа с поддержкой смартфонов и экономичный расход — преемник Cobalt в городе."
  },
  {
    id: "tracker",
    name: "Chevrolet Tracker",
    tagline: "Кроссовер для уверенных решений",
    body: "Кроссовер",
    priceFromUZS: 250700000,
    priceFromUSD: 19900,
    engine: "1.2 л турбо, 132 л.с.",
    transmission: "6АТ",
    fuel: "Бензин",
    description: "Компактный кроссовер с турбодвигателем и богатым оснащением. Один из бестселлеров сегмента SUV в Узбекистане."
  },
  {
    id: "malibu-xl",
    name: "Chevrolet Malibu XL",
    tagline: "Бизнес-класс без компромиссов",
    body: "Седан",
    priceFromUZS: 384300000,
    priceFromUSD: 30500,
    engine: "2.0 л турбо, 240 л.с.",
    transmission: "9АТ",
    fuel: "Бензин",
    description: "Флагманский седан с 240-сильным турбомотором и удлинённой базой — выбор руководителей и служб такси бизнес-класса."
  },
  {
    id: "damas",
    name: "Chevrolet Damas",
    tagline: "Легенда малого бизнеса",
    body: "Минивэн",
    priceFromUZS: 107100000,
    priceFromUSD: 8500,
    engine: "0.8 л, 38 л.с.",
    transmission: "5МТ",
    fuel: "Бензин/газ",
    description: "Компактный минивэн, на котором держится половина торговли страны. Дешевле в содержании не бывает."
  },
  {
    id: "labo",
    name: "Chevrolet Labo",
    tagline: "Рабочая лошадка на каждый день",
    body: "Пикап",
    priceFromUZS: 112100000,
    priceFromUSD: 8900,
    engine: "0.8 л, 38 л.с.",
    transmission: "5МТ",
    fuel: "Бензин/газ",
    description: "Лёгкий пикап для перевозок по городу и рынкам. Грузоподъёмность до 550 кг при минимальном расходе."
  },
  {
    id: "equinox",
    name: "Chevrolet Equinox",
    tagline: "Кроссовер американского характера",
    body: "Кроссовер",
    priceFromUZS: 427100000,
    priceFromUSD: 33900,
    engine: "1.5 л турбо, 172 л.с.",
    transmission: "6АТ",
    fuel: "Бензин",
    description: "Среднеразмерный кроссовер с просторным салоном и полным набором систем безопасности."
  },
  {
    id: "traverse",
    name: "Chevrolet Traverse",
    tagline: "Семь мест. Ноль компромиссов",
    body: "Кроссовер",
    priceFromUZS: 655200000,
    priceFromUSD: 52000,
    engine: "2.5 л турбо, 315 л.с.",
    transmission: "8АТ",
    fuel: "Бензин",
    description: "Трёхрядный кроссовер для большой семьи: 315 сил, полный привод и багажник, который вмещает всё."
  },
  {
    id: "tahoe",
    name: "Chevrolet Tahoe",
    tagline: "Икона больших дорог",
    body: "Внедорожник",
    priceFromUZS: 1026900000,
    priceFromUSD: 81500,
    engine: "6.2 л V8, 426 л.с.",
    transmission: "10АТ",
    fuel: "Бензин",
    description: "Полноразмерный внедорожник с атмосферным V8. Статус, комфорт и присутствие, которое не требует слов."
  },
  {
    id: "spark",
    name: "Chevrolet Spark",
    tagline: "Компактный. Манёвренный. Свой",
    body: "Хэтчбек",
    priceFromUZS: 123500000,
    priceFromUSD: 9800,
    engine: "1.25 л, 85 л.с.",
    transmission: "4АТ / 5МТ",
    fuel: "Бензин/газ",
    description: "Городской хэтчбек, снятый с производства, но по-прежнему один из самых востребованных на вторичном рынке."
  }
];

window.UZ_LISTINGS = [
  {
    id: 1,
    modelId: "cobalt",
    title: "Chevrolet Cobalt 4-позиция",
    year: 2026,
    priceUSD: 13400,
    priceUZS: 168800000,
    mileageKm: 0,
    condition: "new",
    region: "Ташкент",
    transmission: "Автомат",
    fuel: "Бензин",
    color: "Белый",
    sellerType: "Дилер",
    posted: "2026-07-06",
    vinChecked: true,
    premium: true,
    description: "Новый Cobalt 4-позиция в максимальной комплектации у официального дилера. Автомат, кондиционер, электропакет по кругу. Оформление и постановка на учёт в день обращения.",
    specs: { "Двигатель": "1.5 л", "Мощность": "106 л.с.", "КПП": "6АТ", "Привод": "Передний", "Кузов": "Седан", "Гарантия": "3 года / 100 000 км" }
  },
  {
    id: 2,
    modelId: "cobalt",
    title: "Chevrolet Cobalt 2-позиция",
    year: 2020,
    priceUSD: 9500,
    priceUZS: 119700000,
    mileageKm: 82000,
    condition: "used",
    region: "Фергана",
    transmission: "Механика",
    fuel: "Бензин/газ",
    color: "Белый",
    sellerType: "Частное лицо",
    posted: "2026-06-14",
    vinChecked: true,
    premium: false,
    description: "Продаю Cobalt 2-позиция, один хозяин, вся история обслуживания на руках. Метан установлен официально, документы в порядке. Торг у капота.",
    specs: { "Двигатель": "1.5 л", "Мощность": "106 л.с.", "КПП": "5МТ", "Привод": "Передний", "Кузов": "Седан", "Владельцев": "1", "ГБО": "Метан" }
  },
  {
    id: 3,
    modelId: "cobalt",
    title: "Chevrolet Cobalt 4-позиция",
    year: 2023,
    priceUSD: 11600,
    priceUZS: 146200000,
    mileageKm: 41000,
    condition: "used",
    region: "Ташкент",
    transmission: "Автомат",
    fuel: "Бензин",
    color: "Серебристый",
    sellerType: "Частное лицо",
    posted: "2026-07-02",
    vinChecked: true,
    premium: false,
    description: "Автомат, состояние отличное, не крашен, не бит. Обслуживался только у официалов, масло менялось каждые 8 тысяч. Причина продажи — переход на Tracker.",
    specs: { "Двигатель": "1.5 л", "Мощность": "106 л.с.", "КПП": "6АТ", "Привод": "Передний", "Кузов": "Седан", "Владельцев": "1" }
  },
  {
    id: 4,
    modelId: "cobalt",
    title: "Chevrolet Cobalt 2-позиция",
    year: 2018,
    priceUSD: 8200,
    priceUZS: 103300000,
    mileageKm: 132000,
    condition: "used",
    region: "Наманган",
    transmission: "Механика",
    fuel: "Бензин/газ",
    color: "Бежевый",
    sellerType: "Частное лицо",
    posted: "2026-06-08",
    vinChecked: false,
    premium: false,
    description: "Рабочая машина, ездит каждый день. По кузову есть мелкие сколы, по технике вопросов нет. Газ-бензин, расход копеечный.",
    specs: { "Двигатель": "1.5 л", "Мощность": "106 л.с.", "КПП": "5МТ", "Привод": "Передний", "Кузов": "Седан", "Владельцев": "2", "ГБО": "Пропан" }
  },
  {
    id: 5,
    modelId: "onix",
    title: "Chevrolet Onix Premier",
    year: 2026,
    priceUSD: 16900,
    priceUZS: 212900000,
    mileageKm: 0,
    condition: "new",
    region: "Ташкент",
    transmission: "Автомат",
    fuel: "Бензин",
    color: "Красный",
    sellerType: "Дилер",
    posted: "2026-07-04",
    vinChecked: true,
    premium: true,
    description: "Onix Premier в наличии у дилера: турбомотор, камера заднего вида, беспроводной CarPlay. Доступен автокредит от 4% на первый год. Выдача — сразу после оплаты.",
    specs: { "Двигатель": "1.0 л турбо", "Мощность": "116 л.с.", "КПП": "6АТ", "Привод": "Передний", "Кузов": "Седан", "Гарантия": "3 года / 100 000 км" }
  },
  {
    id: 6,
    modelId: "onix",
    title: "Chevrolet Onix LT",
    year: 2024,
    priceUSD: 13800,
    priceUZS: 173900000,
    mileageKm: 28000,
    condition: "used",
    region: "Самарканд",
    transmission: "Автомат",
    fuel: "Бензин",
    color: "Серый",
    sellerType: "Частное лицо",
    posted: "2026-06-21",
    vinChecked: true,
    premium: false,
    description: "Onix LT в идеальном состоянии, брал новым в салоне. Пробег честный, весь по Самарканду. Продаю в связи с отъездом, документы готовы к быстрой сделке.",
    specs: { "Двигатель": "1.0 л турбо", "Мощность": "116 л.с.", "КПП": "6АТ", "Привод": "Передний", "Кузов": "Седан", "Владельцев": "1" }
  },
  {
    id: 7,
    modelId: "tracker",
    title: "Chevrolet Tracker LT",
    year: 2026,
    priceUSD: 20500,
    priceUZS: 258300000,
    mileageKm: 0,
    condition: "new",
    region: "Ташкент",
    transmission: "Автомат",
    fuel: "Бензин",
    color: "Синий",
    sellerType: "Дилер",
    posted: "2026-07-07",
    vinChecked: true,
    premium: true,
    description: "Новый Tracker LT со склада дилера, без очереди и переплат. Турбодвигатель 1.2, светодиодная оптика, климат-контроль. Возможен trade-in вашего авто.",
    specs: { "Двигатель": "1.2 л турбо", "Мощность": "132 л.с.", "КПП": "6АТ", "Привод": "Передний", "Кузов": "Кроссовер", "Гарантия": "3 года / 100 000 км" }
  },
  {
    id: 8,
    modelId: "tracker",
    title: "Chevrolet Tracker Premier",
    year: 2022,
    priceUSD: 16200,
    priceUZS: 204100000,
    mileageKm: 64000,
    condition: "used",
    region: "Андижан",
    transmission: "Автомат",
    fuel: "Бензин",
    color: "Чёрный",
    sellerType: "Частное лицо",
    posted: "2026-06-11",
    vinChecked: true,
    premium: false,
    description: "Tracker Premier, полная комплектация: люк, кожа, обогревы. Вложений не требует, сел и поехал. Реальному покупателю уступлю.",
    specs: { "Двигатель": "1.2 л турбо", "Мощность": "132 л.с.", "КПП": "6АТ", "Привод": "Передний", "Кузов": "Кроссовер", "Владельцев": "1", "Люк": "Есть" }
  },
  {
    id: 9,
    modelId: "tracker",
    title: "Chevrolet Tracker LT",
    year: 2023,
    priceUSD: 17800,
    priceUZS: 224300000,
    mileageKm: 39000,
    condition: "used",
    region: "Ташкент",
    transmission: "Автомат",
    fuel: "Бензин",
    color: "Белый",
    sellerType: "Частное лицо",
    posted: "2026-06-28",
    vinChecked: true,
    premium: false,
    description: "Машина в состоянии новой, пробег подтверждается сервисной книжкой. Зимой стояла в гараже, летом — только город. Обмен не интересует, только продажа.",
    specs: { "Двигатель": "1.2 л турбо", "Мощность": "132 л.с.", "КПП": "6АТ", "Привод": "Передний", "Кузов": "Кроссовер", "Владельцев": "1" }
  },
  {
    id: 10,
    modelId: "malibu-xl",
    title: "Chevrolet Malibu XL Premier",
    year: 2026,
    priceUSD: 31200,
    priceUZS: 393100000,
    mileageKm: 0,
    condition: "new",
    region: "Ташкент",
    transmission: "Автомат",
    fuel: "Бензин",
    color: "Чёрный",
    sellerType: "Дилер",
    posted: "2026-07-05",
    vinChecked: true,
    premium: true,
    description: "Флагманский Malibu XL Premier: 240 л.с., панорамная крыша, вентиляция сидений, Bose. Автомобиль в наличии, тест-драйв в день обращения.",
    specs: { "Двигатель": "2.0 л турбо", "Мощность": "240 л.с.", "КПП": "9АТ", "Привод": "Передний", "Кузов": "Седан", "Гарантия": "3 года / 100 000 км" }
  },
  {
    id: 11,
    modelId: "malibu-xl",
    title: "Chevrolet Malibu XL",
    year: 2021,
    priceUSD: 19500,
    priceUZS: 245700000,
    mileageKm: 88000,
    condition: "used",
    region: "Самарканд",
    transmission: "Автомат",
    fuel: "Бензин",
    color: "Белый",
    sellerType: "Частное лицо",
    posted: "2026-06-17",
    vinChecked: true,
    premium: false,
    description: "Malibu XL 2-й владелец, обслужен по регламенту, коробка адаптирована, масло свежее. Салон чистый, не прокуренный. Смотреть можно в любое время.",
    specs: { "Двигатель": "2.0 л турбо", "Мощность": "240 л.с.", "КПП": "9АТ", "Привод": "Передний", "Кузов": "Седан", "Владельцев": "2" }
  },
  {
    id: 12,
    modelId: "damas",
    title: "Chevrolet Damas DLX",
    year: 2025,
    priceUSD: 8700,
    priceUZS: 109600000,
    mileageKm: 0,
    condition: "new",
    region: "Наманган",
    transmission: "Механика",
    fuel: "Бензин/газ",
    color: "Белый",
    sellerType: "Дилер",
    posted: "2026-06-25",
    vinChecked: true,
    premium: false,
    description: "Новый Damas DLX для работы и семьи. Заводское ГБО, 7 мест, минимальный расход. Оформление лизинга для ИП — за один день.",
    specs: { "Двигатель": "0.8 л", "Мощность": "38 л.с.", "КПП": "5МТ", "Привод": "Задний", "Кузов": "Минивэн", "Мест": "7" }
  },
  {
    id: 13,
    modelId: "damas",
    title: "Chevrolet Damas",
    year: 2019,
    priceUSD: 5800,
    priceUZS: 73100000,
    mileageKm: 120000,
    condition: "used",
    region: "Андижан",
    transmission: "Механика",
    fuel: "Бензин/газ",
    color: "Белый",
    sellerType: "Частное лицо",
    posted: "2026-06-05",
    vinChecked: false,
    premium: false,
    description: "Дамас в рабочем состоянии, возил товар по рынку. Двигатель после ревизии, сцепление новое. Цена окончательная, без торга.",
    specs: { "Двигатель": "0.8 л", "Мощность": "38 л.с.", "КПП": "5МТ", "Привод": "Задний", "Кузов": "Минивэн", "Владельцев": "3", "ГБО": "Пропан" }
  },
  {
    id: 14,
    modelId: "labo",
    title: "Chevrolet Labo Standard",
    year: 2025,
    priceUSD: 9100,
    priceUZS: 114700000,
    mileageKm: 0,
    condition: "new",
    region: "Фергана",
    transmission: "Механика",
    fuel: "Бензин/газ",
    color: "Белый",
    sellerType: "Дилер",
    posted: "2026-06-30",
    vinChecked: true,
    premium: false,
    description: "Новый Labo с бортовой платформой, готов к работе с первого дня. Грузоподъёмность 550 кг, заводская гарантия. Скидка при покупке в лизинг.",
    specs: { "Двигатель": "0.8 л", "Мощность": "38 л.с.", "КПП": "5МТ", "Привод": "Задний", "Кузов": "Пикап", "Грузоподъёмность": "550 кг" }
  },
  {
    id: 15,
    modelId: "labo",
    title: "Chevrolet Labo",
    year: 2020,
    priceUSD: 6200,
    priceUZS: 78100000,
    mileageKm: 95000,
    condition: "used",
    region: "Нукус",
    transmission: "Механика",
    fuel: "Бензин/газ",
    color: "Белый",
    sellerType: "Частное лицо",
    posted: "2026-06-09",
    vinChecked: false,
    premium: false,
    description: "Продаётся Labo, использовался для доставки стройматериалов. Кузов усилен, тент в комплекте. Все расходники поменяны месяц назад.",
    specs: { "Двигатель": "0.8 л", "Мощность": "38 л.с.", "КПП": "5МТ", "Привод": "Задний", "Кузов": "Пикап", "Владельцев": "2", "ГБО": "Пропан" }
  },
  {
    id: 16,
    modelId: "equinox",
    title: "Chevrolet Equinox LT",
    year: 2025,
    priceUSD: 34500,
    priceUZS: 434700000,
    mileageKm: 0,
    condition: "new",
    region: "Ташкент",
    transmission: "Автомат",
    fuel: "Бензин",
    color: "Серый",
    sellerType: "Дилер",
    posted: "2026-06-19",
    vinChecked: true,
    premium: false,
    description: "Equinox LT нового модельного года: адаптивный круиз, панорамная камера, багажник с электроприводом. Один автомобиль в наличии, остальные — под заказ.",
    specs: { "Двигатель": "1.5 л турбо", "Мощность": "172 л.с.", "КПП": "6АТ", "Привод": "Передний", "Кузов": "Кроссовер", "Гарантия": "3 года / 100 000 км" }
  },
  {
    id: 17,
    modelId: "equinox",
    title: "Chevrolet Equinox Premier",
    year: 2023,
    priceUSD: 26800,
    priceUZS: 337700000,
    mileageKm: 45000,
    condition: "used",
    region: "Ташкент",
    transmission: "Автомат",
    fuel: "Бензин",
    color: "Чёрный",
    sellerType: "Частное лицо",
    posted: "2026-07-01",
    vinChecked: true,
    premium: false,
    description: "Equinox Premier из первых рук, привезён официально. Полная комплектация, зимняя резина на дисках в подарок. VIN проверен, история чистая.",
    specs: { "Двигатель": "1.5 л турбо", "Мощность": "172 л.с.", "КПП": "6АТ", "Привод": "Передний", "Кузов": "Кроссовер", "Владельцев": "1" }
  },
  {
    id: 18,
    modelId: "traverse",
    title: "Chevrolet Traverse RS",
    year: 2026,
    priceUSD: 53900,
    priceUZS: 679100000,
    mileageKm: 0,
    condition: "new",
    region: "Ташкент",
    transmission: "Автомат",
    fuel: "Бензин",
    color: "Белый",
    sellerType: "Дилер",
    posted: "2026-07-03",
    vinChecked: true,
    premium: false,
    description: "Новый Traverse RS: 315 л.с., полный привод, 7 мест и два люка. Редкая комплектация в наличии — не под заказ. Trade-in и кредит без первоначального взноса.",
    specs: { "Двигатель": "2.5 л турбо", "Мощность": "315 л.с.", "КПП": "8АТ", "Привод": "Полный", "Кузов": "Кроссовер", "Мест": "7" }
  },
  {
    id: 19,
    modelId: "tahoe",
    title: "Chevrolet Tahoe Premier",
    year: 2023,
    priceUSD: 72000,
    priceUZS: 907200000,
    mileageKm: 38000,
    condition: "used",
    region: "Ташкент",
    transmission: "Автомат",
    fuel: "Бензин",
    color: "Чёрный",
    sellerType: "Частное лицо",
    posted: "2026-06-23",
    vinChecked: true,
    premium: false,
    description: "Tahoe Premier 6.2 в максимальной комплектации, обслуживался только у дилера. Пневмоподвеска, задний экран для пассажиров, состояние без нареканий. Серьёзному покупателю — разумный торг.",
    specs: { "Двигатель": "6.2 л V8", "Мощность": "426 л.с.", "КПП": "10АТ", "Привод": "Полный", "Кузов": "Внедорожник", "Владельцев": "1", "Мест": "7" }
  },
  {
    id: 20,
    modelId: "tahoe",
    title: "Chevrolet Tahoe High Country",
    year: 2026,
    priceUSD: 82000,
    priceUZS: 1033200000,
    mileageKm: 0,
    condition: "new",
    region: "Ташкент",
    transmission: "Автомат",
    fuel: "Бензин",
    color: "Чёрный",
    sellerType: "Дилер",
    posted: "2026-06-27",
    vinChecked: true,
    premium: false,
    description: "Tahoe High Country нового модельного года в шоуруме. V8 6.2, пневмоподвеска Air Ride, отделка кожей полуанилин. Персональный менеджер и выдача в течение недели.",
    specs: { "Двигатель": "6.2 л V8", "Мощность": "426 л.с.", "КПП": "10АТ", "Привод": "Полный", "Кузов": "Внедорожник", "Мест": "7", "Гарантия": "3 года / 100 000 км" }
  },
  {
    id: 21,
    modelId: "spark",
    title: "Chevrolet Spark LS",
    year: 2019,
    priceUSD: 6300,
    priceUZS: 79400000,
    mileageKm: 98000,
    condition: "used",
    region: "Бухара",
    transmission: "Механика",
    fuel: "Бензин/газ",
    color: "Красный",
    sellerType: "Частное лицо",
    posted: "2026-06-12",
    vinChecked: false,
    premium: false,
    description: "Спарк на каждый день: заводится с полоборота, кондиционер холодит. По кузову пара царапин, по цене учтено. Первый взнос — и машина ваша.",
    specs: { "Двигатель": "1.25 л", "Мощность": "85 л.с.", "КПП": "5МТ", "Привод": "Передний", "Кузов": "Хэтчбек", "Владельцев": "2", "ГБО": "Пропан" }
  },
  {
    id: 22,
    modelId: "spark",
    title: "Chevrolet Spark LT",
    year: 2021,
    priceUSD: 7400,
    priceUZS: 93200000,
    mileageKm: 54000,
    condition: "used",
    region: "Карши",
    transmission: "Автомат",
    fuel: "Бензин",
    color: "Серый",
    sellerType: "Частное лицо",
    posted: "2026-07-08",
    vinChecked: true,
    premium: false,
    description: "Spark LT на автомате — идеален для города и начинающего водителя. Женщина за рулём, аккуратная эксплуатация, ни одного окраса. Продажа без посредников.",
    specs: { "Двигатель": "1.25 л", "Мощность": "85 л.с.", "КПП": "4АТ", "Привод": "Передний", "Кузов": "Хэтчбек", "Владельцев": "1" }
  }
];

window.UZ_HELPERS = {
  fmtUZS: function (n) { return n.toLocaleString("ru-RU") + " сум"; },
  fmtUSD: function (n) { return "$" + n.toLocaleString("en-US"); },
  fmtKm: function (n) { return n === 0 ? "Новый" : n.toLocaleString("ru-RU") + " км"; }
};
